name: CMake Desktop

on:
  push:
    paths:
      - 'desktop/revision.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        mkdir desktop/build
        cmake -S desktop -B desktop/build
        cd desktop/build
    - name: Build for Windows x86_64
      run: cmake --build . --config Release --target install -- -march=x86-64
    - name: Build for Windows x86
      run: cmake --build . --config Release --target install -- -march=i686
    - name: Build for Linux x86_64
      run: cmake --build . --config Release --target install -- -march=x86-64
    - name: Build for Linux x86
      run: cmake --build . --config Release --target install -- -march=i686
    - name: Build for Linux arm64
      run: cmake --build . --config Release --target install -- -march=arm64
    - name: Build for MacOS x86_64
      run: cmake --build . --config Release --target install -- -march=x86-64
    - name: Configure CMake End
      run: cd ../../
    - name: Upload an Build Cmake Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Cmake-Build
        path: ${{ github.workspace }}/desktop/build
