name: CMake Desktop

on:
  push:
    paths:
      - 'desktop/revision.txt'

jobs:
  build:
  	strategy:
		  matrix:
      - os: windows
        arch: x86_64
      - os: windows
        arch: i686
      - os: linux
        arch: x86
      - os: linux
        arch: x86_64
      - os: linux
        arch: aarch64
      - os: macos
        arch: x86_64
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: Build CMake for ${{ matrix.os }} ${{mattix.arch}}
      run: |
        mkdir desktop/build
        cmake -S desktop -B desktop/${{ matrix.os }}-${{ matrix.arch }}-build
        cd desktop/${{ matrix.os }}-${{ matrix.arch }}-build
        cmake --build . --config Release -march=${{ matrix.arch }}
        cd ../../
    - name: Upload an Build Cmake Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Cmake-${{ matrix.os }}_${{ matrix.arch }}-build
        path: ${{ github.workspace }}/desktop/${{ matrix.os }}-${{ matrix.arch }}-build
