name: CMake Desktop

on:
  push:
    paths:
      - 'desktop/revision.txt'

jobs:
  build:
    strategy:
      matrix
        include:
	        - name: ubuntu
	          os: ubuntu-latest
	        - name: windows
	          os: windows-latest
	        - name: macOS
	          os: macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        mkdir desktop/build-${{ matrix.name }}
        cd desktop/build-${{ matrix.name }}
        cmake .. 
        cmake --build .
        cd ../../
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: All-Make-${{ matrix.name }}
        path: ${{ github.workspace }}/desktop/build-${{ matrix.name }}
