name: CMake Desktop

on:
  push:
    paths:
      - 'desktop/revision.txt'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: |
          mkdir desktop/${{ matrix.os }}-build
          cd desktop/${{ matrix.os }}-build
          cmake .. 
          cmake --build .
          cd ../../
      - name: Upload an Build Cmake Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cmake-${{ matrix.os }}
          path: ${{ github.workspace }}/desktop/${{ matrix.os }}-build
