name: Formating Clang Code

on:
  push:
    paths:
      - 'cpp-formatting.txt'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and run clang-format
        run: |
        	sudo apt-get install clang-format
        	clang-format -i **/*.cpp **/*.h
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Auto-format code with clang-format"
          add: "**/*.cpp **/*.h"
